// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVim
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenIn.f9ec1140-9c52-4362-b8e1-2afdcd99a7ef";
        public const string Name = "OpenIn";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alarm.com";
        public const string Tags = "";
    }
}
